mode: "dev"
port: 8081
start_time: "2023-09-28"
machine_id : 1
log:
  level: "debug"
  filename: "./log/bluebell.log"
  max_size: 1000
  max_age: 3600
  max_backups: 5

auth:
  refreshTokenTime: 24 * 365
mysql:
  host: 127.0.0.1
  port: 3306
  user: debian-sys-maint
  password: gk970928
  db: bluebell
  max_open_conns: 100
  max_idle_conns: 20

redis:
  host: 127.0.0.1
  port: 16379
  db: 0